services:
  - name: web
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT your_app_module:app
    env:
      - key: PYTHONUNBUFFERED
        value: "1"
